structure, main styles were done
polinadudchenko/team-project-html pull request #1
Opened 2021-06-03 15:16 UTC by polinadudchenko

fonts were downloaded and imported to project
html partials were created
scss partials and whole structure were created
common.scss, container.scss were added
breakpoints as mixin were added in breakpoints.scss
first variables were created

2021-06-03 17:12 UTC, tatiana-borisova requested changes

2021-06-03 17:12 UTC, tatiana-borisova commented on src/partials/example.html
> -</article>
ИМХО надо оставить то, что написано в этом файле для всех остальных до конца проекта, просто не подключать к проекту

2021-06-03 17:12 UTC, tatiana-borisova commented on src/sass/_example.scss
> -}
Здесь то же самое. Хорошие советы, которых явно многие еще не видели

2021-06-03 17:12 UTC, tatiana-borisova commented on src/sass/base/_common.scss
> +h3,
h4, h5, h6 на всякий случай, мы не знаем, как остальные пишут

2021-06-03 17:12 UTC, tatiana-borisova commented on src/sass/base/_container.scss
> +
Полина, объясни мне, пожалуйста, почему не дать автомарджины сюда, а не только на мобилку?

2021-06-03 17:12 UTC, tatiana-borisova commented on src/sass/utils/_varianbles.scss
> +$grau-text-color: #907e82;
По-немецки написала))))

2021-06-03 17:12 UTC, tatiana-borisova commented on src/sass/utils/_varianbles.scss
> +$card-set-gap: 20px;
не, они везде разные для разных девайсов, да и надо пополам делить, чтобы на все 4 стороны задать, если я поняла, о чем ты

2021-06-03 18:00 UTC, DiorditsaVlad reviewed
спросить у ментора по поводу шрифтов

2021-06-03 20:32 UTC, VladimyrK commented on src/sass/utils/_varianbles.scss
> +$grau-text-color: #907e82;
Называть переменные текущими цветами будет некорректно, так как смысл перерменных в том что цвет может поменяться и тогда название такой переменной потеряет смысл. Нужно что-то типа main-text-color, main-bg-color, secondary-text-color, main-accent-color. Можно пересмотреть код барбершопа Юлии, как она называла переменные.

2021-06-03 20:34 UTC, VladimyrK commented on src/sass/utils/_varianbles.scss
> +$grau-text-color: #907e82;
Название паршала _variables а не varianbles - очепяточка :)

2021-06-04 07:31 UTC, polinadudchenko commented on src/partials/example.html
> -</article>
ок, верну

2021-06-04 07:31 UTC, polinadudchenko commented on src/sass/_example.scss
> -}
верну

2021-06-04 07:31 UTC, polinadudchenko commented on src/sass/base/_common.scss
> +h3,
добавлю

2021-06-04 07:35 UTC, polinadudchenko commented on src/sass/base/_container.scss
> +
начальные настройки прописаны для экранов от 320 и так как контент занимает ширину всего экрана, то нет смысла ставить марджины для центрирования, а вот для экранов от 480 и дальше они уже нужны

2021-06-04 07:35 UTC, polinadudchenko commented on src/sass/utils/_varianbles.scss
> +$grau-text-color: #907e82;
блин!

2021-06-04 07:39 UTC, polinadudchenko commented on src/sass/utils/_varianbles.scss
> +$card-set-gap: 20px;
тогда я убираю эту переменную. Но я вообще не давала половину, я просто минусовые марджины потом давала только слева и сверху

2021-06-04 09:10 UTC, polinadudchenko commented on src/sass/utils/_varianbles.scss
> +$grau-text-color: #907e82;
@VladimyrK оно понятно, но вот я не могу сказать, какой цвет текста main, а какой secondary. И с переменными по цветам всем вместе, коненчо, проще будет работать

2021-06-04 16:47 UTC, tatiana-borisova approved these changes

2021-06-05 06:39 UTC, merged